package org.adox.app.view.aplicacion;

import java.util.logging.Level;
import java.util.logging.Logger;
import javax.swing.JOptionPane;
import org.adox.app.Main;
import org.adox.app.common.ConstantesApp;
import org.adox.app.config.ServicioSpring;
import org.adox.app.util.BackupUtil;

/**
 * @author Adolfo
 ifBackup.java
 Created on 28-mar-2011, 3:41:51
 http://www.desarrolloweb.com/articulos/1202.php
 http://dev.mysql.com/doc/refman/5.0/es/mysqldump.html
 http://linuxcommand.org/man_pages/mysqldump1.html
 */
public class ifBackup extends javax.swing.JFrame {

    ServicioSpring aop;
    BackupUtil oBackUpSample;
    int estado = 0;
    String restaura = "";

    public ifBackup(ServicioSpring oSpring) {
        initComponents();
        estado = 1;
        ConstantesApp.APP = 1;
        aop = oSpring;
    }

    public ifBackup(int i, ServicioSpring oSpring) {
        initComponents();
        estado = 0;
        ConstantesApp.APP = 1;
        aop = oSpring;
        btnBackup.setEnabled(false);
        btnRestarurar.setEnabled(false);
    }

    /** This method is called from within the constructor to
     * initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is
     * always regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jPanel2 = new javax.swing.JPanel();
        jLabel2 = new javax.swing.JLabel();
        btnRestarurar = new javax.swing.JButton();
        jPanel1 = new javax.swing.JPanel();
        jLabel1 = new javax.swing.JLabel();
        btnBackup = new javax.swing.JButton();

        setDefaultCloseOperation(javax.swing.WindowConstants.DISPOSE_ON_CLOSE);
        setTitle("::: GESTION DE RESPALDOS DEL SISTEMA :::");

        jPanel2.setBackground(new java.awt.Color(255, 255, 255));
        jPanel2.setName("jPanel2"); // NOI18N

        jLabel2.setFont(new java.awt.Font("Tahoma", 1, 18));
        jLabel2.setForeground(new java.awt.Color(153, 0, 0));
        jLabel2.setText("RESTAURAR COPIA DE SEGURIDAD");
        jLabel2.setName("jLabel2"); // NOI18N

        btnRestarurar.setIcon(new javax.swing.ImageIcon(getClass().getResource("/org/adox/app/resources/imagenes/m_actualizar.png"))); // NOI18N
        btnRestarurar.setText("RESTAURAR");
        btnRestarurar.setHorizontalTextPosition(javax.swing.SwingConstants.CENTER);
        btnRestarurar.setName("btnRestarurar"); // NOI18N
        btnRestarurar.setVerticalAlignment(javax.swing.SwingConstants.BOTTOM);
        btnRestarurar.setVerticalTextPosition(javax.swing.SwingConstants.BOTTOM);
        btnRestarurar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnRestarurarActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout jPanel2Layout = new javax.swing.GroupLayout(jPanel2);
        jPanel2.setLayout(jPanel2Layout);
        jPanel2Layout.setHorizontalGroup(
            jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel2Layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jLabel2, javax.swing.GroupLayout.PREFERRED_SIZE, 327, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(btnRestarurar)
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );
        jPanel2Layout.setVerticalGroup(
            jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel2Layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING, false)
                    .addComponent(jLabel2, javax.swing.GroupLayout.Alignment.LEADING, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(btnRestarurar, javax.swing.GroupLayout.Alignment.LEADING, javax.swing.GroupLayout.DEFAULT_SIZE, 67, Short.MAX_VALUE))
                .addContainerGap())
        );

        jPanel1.setBackground(new java.awt.Color(255, 255, 255));
        jPanel1.setName("jPanel1"); // NOI18N

        jLabel1.setFont(new java.awt.Font("Tahoma", 1, 18));
        jLabel1.setForeground(new java.awt.Color(153, 0, 0));
        jLabel1.setText("REALIZAR COPIA DE SEGURIDAD");
        jLabel1.setName("jLabel1"); // NOI18N

        btnBackup.setIcon(new javax.swing.ImageIcon(getClass().getResource("/org/adox/app/resources/imagenes/btn_play.png"))); // NOI18N
        btnBackup.setText("BACKUP");
        btnBackup.setHorizontalTextPosition(javax.swing.SwingConstants.CENTER);
        btnBackup.setName("btnBackup"); // NOI18N
        btnBackup.setVerticalAlignment(javax.swing.SwingConstants.BOTTOM);
        btnBackup.setVerticalTextPosition(javax.swing.SwingConstants.BOTTOM);
        btnBackup.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnBackupActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout jPanel1Layout = new javax.swing.GroupLayout(jPanel1);
        jPanel1.setLayout(jPanel1Layout);
        jPanel1Layout.setHorizontalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jLabel1, javax.swing.GroupLayout.PREFERRED_SIZE, 327, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(btnBackup, javax.swing.GroupLayout.DEFAULT_SIZE, 93, Short.MAX_VALUE)
                .addContainerGap())
        );
        jPanel1Layout.setVerticalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(btnBackup)
                    .addComponent(jLabel1, javax.swing.GroupLayout.PREFERRED_SIZE, 46, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addContainerGap(27, Short.MAX_VALUE))
        );

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING, false)
                    .addComponent(jPanel1, javax.swing.GroupLayout.Alignment.LEADING, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(jPanel2, javax.swing.GroupLayout.Alignment.LEADING, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jPanel1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(jPanel2, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void btnRestarurarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnRestarurarActionPerformed
        Restaurar();

}//GEN-LAST:event_btnRestarurarActionPerformed

    private void btnBackupActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnBackupActionPerformed
        Backup();
}//GEN-LAST:event_btnBackupActionPerformed

    public void ejec() {
        switch (estado) {
            case 0:
                System.out.println("entro a cero");
                dispose();
                Main oMain = new Main();
                oMain.main(null);
                break;
            case 1:
                System.out.println("entro a uno");
                dispose();
                break;
        }

    }

  
    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton btnBackup;
    private javax.swing.JButton btnRestarurar;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JPanel jPanel2;
    // End of variables declaration//GEN-END:variables

    private void Backup() {
        int rpta = JOptionPane.showConfirmDialog(this, "DESEA REALIZAR LA BACKUP DE LA BASE DE DATOS?", "COPIA DE SEGURIDAD", JOptionPane.YES_NO_OPTION);
        if (rpta == 0) {
            try {
                oBackUpSample = new BackupUtil(this);
                oBackUpSample.GenerarBackupMySQL();
                restaura = "1";
                System.out.println(" Se termino el bakup ");
            } catch (Exception ex) {
                Logger.getLogger(ifBackup.class.getName()).log(Level.SEVERE, null, ex);
            }

            do {
                System.out.println(" esperando ");
            } while (restaura.equals(""));

            System.out.println(" fin de espera");
            ejec();
        }
    }

    private void Restaurar() {
        int rpta = JOptionPane.showConfirmDialog(this, "DESEA RESTAURAR LA BASE DE DATOS?", "COPIA DE SEGURIDAD", JOptionPane.YES_NO_OPTION);
        if (rpta == 0) {
            try {
                oBackUpSample = new BackupUtil(this);
                oBackUpSample.RestaurarBackup(aop);
                restaura = "1";
            } catch (Exception ex) {
                Logger.getLogger(ifBackup.class.getName()).log(Level.SEVERE, null, ex);
            }

            do {
                System.out.println(" esperando ");
            } while (restaura.equals(""));

            System.out.println(" fin de espera");
            ejec();
        }
    }
}
